name: Org Development
favicon: null
layout_spectrum: 0.26827
typography_spectrum: 0.7146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5801822477951646
  lightness: 0.5117804920300841
  saturation: 0.5491345047485083
  rhythmicContrast: 0.014221168123185635
purpose: []
